---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2
  # TODO: Uncomment synced_folders to test local mixlib-install builds
  # synced_folders:
    # - ["path/to/mixlib-install/pkg", "/pkg"]

provisioner:
  # TODO: (engineering-services) Switch this back to policyfile_zero
  # when kitchen supports named run lists for suites.
  name: chef_zero
  data_bags_path: test/fixtures/data_bags

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private
  - name: windows-server-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard # private
      customize:
        cpus: 4

suites:
  - name: default
    excludes: [ 'macosx-10.10', 'windows-server-2012r2-standard' ]
    run_list:
      - recipe[test]
      - recipe[test::repo]

  - name: local_package_install
    excludes: [ 'macosx-10.10', 'windows-server-2012r2-standard' ]
    run_list:
      - recipe[test]
      - recipe[test::local]

  - name: chefdk
    run_list:
      - recipe[test::chefdk]

  # Tests that require access to Chef's internal network
  <% if ENV['ARTIFACTORY_USERNAME'] %>
  - name: unstable_chefdk
    provisioner:
      product_name: chefdk
      product_version: latest
      channel: stable
    excludes: [ 'macosx-10.10', 'windows-server-2012r2-standard' ]
    run_list:
      - recipe[test::unstable_chefdk]
    attributes:
      artifactory:
        username: <%= ENV['ARTIFACTORY_USERNAME'] %>
        password: <%= ENV['ARTIFACTORY_PASSWORD'] %>

  - name: unstable_chef_server
    excludes: [ 'macosx-10.10', 'windows-server-2012r2-standard' ]
    run_list:
      - recipe[test::unstable_chef_server]
    attributes:
      artifactory:
        username: <%= ENV['ARTIFACTORY_USERNAME'] %>
        password: <%= ENV['ARTIFACTORY_PASSWORD'] %>
  <% end %>

  - name: push_client
    # we don't yet have push client packages for trusty, only precise
    excludes: [ 'ubuntu-14.04', 'macosx-10.10', 'windows-server-2012r2-standard' ]
    run_list:
      - recipe[test::push]
